name: Check Links
on: push

jobs:
  Check-Website-Links:
    runs-on: ubuntu-latest

    steps:
      - uses: CannonLock/test_links@master
        with:
          file_ignore: "/./about/organization/index.html/, /./about/index.html/, /./myosg-decommissioned/index.html/, /./osg-twiki-decommissioned/index.html/, /./ticket-decommissioned/index.html/, /./voms-retirement/index.html/"
